# Generated by Django 2.2.5 on 2020-11-22 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prodavnica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Korpa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv_korpe', models.CharField(default='Neimenovana korpa', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SadrzajKorpe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('korpa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kupovina.Korpa')),
                ('proizvod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prodavnica.Proizvod')),
            ],
        ),
    ]
