# Generated by Django 2.2.5 on 2020-11-22 18:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proizvod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=120)),
                ('naslovna_slika', models.ImageField(default='', upload_to='')),
                ('cena', models.FloatField()),
                ('datum_dodavanja', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='SpecifikacijeProizvoda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv_specifikacije', models.CharField(max_length=60)),
                ('vrednost_specifikacije', models.CharField(max_length=200)),
                ('proizvod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prodavnica.Proizvod')),
            ],
        ),
        migrations.CreateModel(
            name='ProizvodiSlike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slika_proizvoda', models.ImageField(upload_to='')),
                ('proizvod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prodavnica.Proizvod')),
            ],
        ),
        migrations.CreateModel(
            name='GrupaProizvoda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv_grupe', models.CharField(max_length=100)),
                ('proizvod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prodavnica.Proizvod')),
            ],
        ),
    ]
