# Generated by Django 2.2.5 on 2020-11-22 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodavnica', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proizvod',
            name='naslovna_slika',
            field=models.ImageField(upload_to=''),
        ),
    ]
