# Generated by Django 2.2.5 on 2020-11-22 17:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('korisnici', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='korisnik',
            name='vreme_kreiranja_naloga',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
